In [3]:
#Mingiziem Excercise 1 about pandas 
import pandas
pandas.__version__
#check the version of pandas


'1.0.1'

In [5]:

import numpy 
numpy.__version__

'1.18.1'

In [23]:
import pandas as pd 
import numpy as np
#importing numpy as np and pandas as pd 

In [32]:
#To display the documentation of pandas 
#pd?
data =[34, 5,  44, 88]

In [33]:
#Introducing pandas datastrctures series, Datafraims and index

data_s=pd.Series(data)
data_s

0    34
1     5
2    44
3    88
dtype: int64

In [34]:
data_s.values


array([34,  5, 44, 88], dtype=int64)

In [35]:
data_s[1]

5

In [36]:
data_s[1:3]

1     5
2    44
dtype: int64

In [37]:
len(data_s)

4

In [38]:
fin_d=pd.Series([43, 32, 12, 45,87], index=['Name', 'Age', 'Same', 'D','jan'])
#indexing and accessing the item 
fin_d

Name    43
Age     32
Same    12
D       45
jan     87
dtype: int64

In [65]:
#Series as speciallized dictionary 
#https://www.youtube.com/watch?v=cachHfgfDns
popul_dict = {'Addis Ababa': 38332521,
                   'Bahirdar': 26448193,
                   'Hawassa': 19651127,
                   'Mekelle': 19552860,
                   'Dere Dawa': 12882135}
Ethiopia_population = pd.Series(popul_dict)
Ethiopia_population

Addis Ababa    38332521
Bahirdar       26448193
Hawassa        19651127
Mekelle        19552860
Dere Dawa      12882135
dtype: int64

In [42]:
Ethiopia_population['Addis Ababa']

38332521

In [43]:
Ethiopia_population['Addis Ababa':'Mekelle']

Addis Ababa    38332521
Bahirdar       26448193
Hawassa        19651127
Mekelle        19552860
dtype: int64

In [45]:
Ethiopia_population['Bahirdar':'Mekelle']

Bahirdar    26448193
Hawassa     19651127
Mekelle     19552860
dtype: int64

In [46]:
# We will se the indexing later 
# Data Indexing and Selection
#Constructing series objects

In [47]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [56]:
pd.Series([4,2,2,4] ,index=[7,8,8,2])
#Notice that in this case, the Series is populated only with the explicitly identified keys.

7    4
8    2
8    2
2    4
dtype: int64

In [57]:
#Pandas dataframe object 
Ethio_dict ={'Bahirdar':32343, 'Debretabor':343234, 'Wello': 444522, 'Gojjam':3423432, 'Gonder':564332}
pd.Series(Ethio_dict)

Bahirdar        32343
Debretabor     343234
Wello          444522
Gojjam        3423432
Gonder         564332
dtype: int64

In [70]:
Ethio_pdf=pd.DataFrame({'Ethiopian_Population':Ethio_dict, 'Area':popul_dict})
Ethio_pdf

Ethiopian_Population        Area
Bahirdar                  32343.0  26448193.0
Debretabor               343234.0         NaN
Wello                    444522.0         NaN
Gojjam                  3423432.0         NaN
Gonder                   564332.0         NaN
Addis Ababa                   NaN  38332521.0
Hawassa                       NaN  19651127.0
Mekelle                       NaN  19552860.0
Dere Dawa                     NaN  12882135.0

In [71]:
Ethio_pdf.index


Index(['Bahirdar', 'Debretabor', 'Wello', 'Gojjam', 'Gonder', 'Addis Ababa',
       'Hawassa', 'Mekelle', 'Dere Dawa'],
      dtype='object')

In [72]:
Ethio_pdf.columns

Index(['Ethiopian_Population', 'Area'], dtype='object')

In [73]:
#Dataframe as a speciallization of dictionary where dictionary maps a key to a value 
Ethio_pdf['Area']

Bahirdar       26448193.0
Debretabor            NaN
Wello                 NaN
Gojjam                NaN
Gonder                NaN
Addis Ababa    38332521.0
Hawassa        19651127.0
Mekelle        19552860.0
Dere Dawa      12882135.0
Name: Area, dtype: float64

In [77]:
#We can construct dataframe from a series object 
# A single column data frame can be constructed from a single series 
pd.DataFrame(Ethio_dict, columns=['population'])

Empty DataFrame
Columns: [population]
Index: []

In [78]:
#From a list of dictionaries we can create dataframe
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)


a  b
0  0  0
1  1  2
2  2  4

In [79]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [80]:
#Given a two-dimensional array of data, we can create a ``DataFrame`` with any specified column and index names.
#If omitted, an integer index will be used for each:

In [82]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['Asl', 'df'],
             index=['a', 'b', 'c'])


Asl        df
a  0.987712  0.612413
b  0.039329  0.689962
c  0.168383  0.247626

In [84]:
#Pandas index object 
ind=pd.Index([33, 4,2,4,54])
ind

Int64Index([33, 4, 2, 4, 54], dtype='int64')

In [85]:
ind[0]

33

In [86]:
ind[::2]

Int64Index([33, 2, 54], dtype='int64')

In [87]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [92]:
#index as order set 
indA = pd.Index([43, 54,23,87,98])
indB = pd.Index([32,54,65,87,12])


In [93]:
indA & indB # intersection 


Int64Index([54, 87], dtype='int64')

In [94]:
indA | indB

Int64Index([12, 23, 32, 43, 54, 65, 87, 98], dtype='int64')

In [95]:
indA ^ indB

Int64Index([12, 23, 32, 43, 65, 98], dtype='int64')

In [96]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [97]:
data.area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [99]:
data['Density']=data['pop']/data['area']
data

area       pop     Density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [100]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [101]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
Density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [102]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [103]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [104]:
#iloc, loc , ix 
data.iloc[:3, :2]


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127